### ISSUE TITLE
Gone from Curseforge? Also, error: 

### ISSUE THREAD

**Issue by MechaZao** [SLOKnightfall/DragonTrainingManual#4]
The addon seems to be gone from Curseforge? I hope it wasn't abandoned!!

With all the updates, its working very nicely now, with exception to this one error:

```26x CTF:SetPoint(): Wrong object type for function
[string "=[C]"]: in function `SetPoint'
[string "@DragonTrainingManual/Modules/Vigor.lua"]:112: in function `LoadPosition'
[string "@DragonTrainingManual/Modules/Vigor.lua"]:123: in function `CreateVigorFrame'
[string "@DragonTrainingManual/DragonTrainingManual.lua"]:1063: in function <DragonTrainingManual/DragonTrainingManual.lua:1062>

Locals:
(*temporary) = CTF {
 0 = <userdata>
 LoadPosition = <function> defined @DragonTrainingManual/Modules/Vigor.lua:105
 widgets = Frame {
 }
 SavePosition = <function> defined @DragonTrainingManual/Modules/Vigor.lua:100
 Counter = Frame {
 }
}
(*temporary) = "CENTER"
(*temporary) = <table> {
 variablesLoaded = true
 Tabs = <table> {
 }
 fadeInfo = <table> {
 }
 PixelSnapDisabled = true
 firstTimeLoaded = 1
 ContainerFrames = <table> {
 }
}
(*temporary) = "CENTER"
(*temporary) = 0
(*temporary) = 0
```

not sure what it is affecting, because functionality seems fine. 

Thank you for your hard work!

**Comment by SLOKnightfall** [comment]
The addon on curseforge got flagged for moderation review, so I'm dealing with that.  Hopefully it should be back in a day or so.  Until then it is available here or on wago.io

Looking at the error, i think it should be fixed in the most recent version.

**Comment by Daniele-f** [comment]
It's still available on curseforge beta
https://beta.curseforge.com/wow/addons/dragon-training-manual

**Comment by MechaZao** [comment]
Hope the moderation goes smoothly, and thanks for the alternate link! 

the error pasted above is from the most recent version, 1.9.1.
though I can't seem to figure out what triggers it. 

It shows up in bugsack randomly during gameplay, and every time I reload or log in.

**Comment by SLOKnightfall** [comment]
Actually the newest version is 1.9.6  :) https://github.com/SLOKnightfall/DragonTrainingManual/releases/download/1.9.6/DragonTrainingManual-1.9.6.zip

**Comment by Arco-Dielhof** [comment]
Copyright infringement (stealing code from other devs) is a VERY valid reason for your AddOn to be taken down. Especially after the actual owner of the code, tries to reach out to you and you just blatantly ignore them, multiple times, on multiple platforms.

**Comment by Antunes43** [comment]
> 

hey, where can I find out more about this? tomcat spoke about it, but i couldn't understand at the time, i really liked this addon because of the RP flavor stuff and the kind of journal it made on the dragons

**Comment by SLOKnightfall** [comment]
@Arco-Dielhof I only ever saw one message on cursefore and once I did I went through and removed/refactored any similar code.  If you still feel that there any infringement still please point it out.

**Comment by Arco-Dielhof** [comment]
You started extremely disrespectful, by stealing my code. Since you seem to understand licenses, this must have been a conscious, active decision.
You have the audacity to put a big ass Patreon button on your stolen property AddOn page on CurseForge, Wago and GitHub, you also have CurseForge rewards active so you are also making money on CF through stolen content from me.
You ignored me on when I tried to reason with you, multiple times on multiple platforms. I tried on multiple different moments, on multiple days.
You tried to promote the stolen AddOn, on Reddit, trying to get more users, thus more money through some one else their property.
You get shafted by platforms, as they are not happy with you making them host stolen content and then you delete evidence while under investigation by said platforms.

When you realize that multiple other AddOn devs are standing up against your behavior, and more people are picking up about you being a thief, all of a sudden you want to talk? No thank you. You now only have one choice left, which is to take down the entire AddOn which started as stolen property, permanently.

**Comment by SLOKnightfall** [comment]
@Arco-Dielhof   Whoa there.  As I said previously I didn't intend make you think you were being ignored.  The only message that I received was one on curseforge, so I don't know why you are saying that you tried to contact me multiple times when you didn't.  I just rechecked Reddit, wagio, github, & my personal email and there are no messages from you.  And when I did see your message I complied with your request to remove the code which is why I deleted any past version that might have had it.  You are acting like I copied your entire addon's code which I didn't.  I haven't been shafted by any platforms.  Its still up at Wagio, and Github.  And I fully expect it to be back on Curseforge after it has been reviewed, since there is nothing that resembles any of your code in it.
